config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  get '/dashboard', to: 'users#show'
  # resources :users, only: [:new, :create]

  get '/trips', to: 'trips#index'
  post '/trips', to: 'trips#create'
  get '/trips/new', to: 'trips#new'
  get '/trips/:id', to: 'trips#show'
  delete '/trips/:id', to: 'trips#destroy'
  get '/trips/:id/edit', to: 'trips#edit'
  put '/trips/:id', to: 'trips#update'
  get '/trips/:trip_id/stops/:stop_id/addresses/:address_id/edit', to: 'stops#edit'
  put '/trips/:trip_id/stops/:stop_id/addresses/:address_id', to: 'stops#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    if current_user.nil?
      redirect_to '/'
      flash[:error] = "Please Log In"
    else
      @user = current_user
    end
  end

  def address_format(params)
    "#{params[:address]}, #{params[:city]}, #{params[:state]} #{params[:zipcode]}"
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(google_id: auth[:uid])
    if user.nil?
      user = User.create(user_params)
    end

    session[:user_id] = user.id
    flash[:success] = "You have logged in"
    redirect_to '/dashboard'
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = "You have logged out"
    redirect_to '/'
  end

  private

  def auth
    request.env['omniauth.auth']
  end

  def user_params
    {google_id: auth[:uid],
    email: auth[:info][:email],
    token: auth[:credentials][:token],
    image: auth[:info][:image],
    first_name: auth[:info][:first_name],
    last_name: auth[:info][:last_name]}
  end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :require_user

  def edit
    @trip_id = params[:trip_id]
    @address_id = params[:address_id]
    @stop_id = params[:stop_id]
  end

  def update
    address = address_format(params)
    TripFacade.update_address(@user.google_id, params[:trip_id],
                              params[:address_id], address, params[:stop_id])
    redirect_to "/trips/#{params[:trip_id]}"
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :require_user

  def show
    @trip = TripFacade.trip_by_id(@user.google_id, params[:id])
    @stops = StopsFacade.all_stops(@user.google_id, params[:id])
    @start_address = @stops.first.address
    @end_address = @stops.last.address
    @nav = NavFacade.create_nav_object(@start_address, @end_address)
    @weather = WeatherFacade.create_weather_objects(@stops)
  end

  def index
    @trips = TripFacade.all_trips(@user.google_id)
  end

  def new
  end

  def create
    start_address = start_params(params)
    end_address = end_params(params)

    new_trip = TripFacade.create_trip(params[:name], @user.google_id,
                                      params[:departure_date], params[:arrival_date])
    trip_id = trip_id(new_trip.body)

    TripFacade.create_stops(trip_id, @user.google_id, start_address, params[:start_point] )
    TripFacade.create_stops(trip_id, @user.google_id, end_address, params[:end_point])
    flash[:success] = "You've Created a New Adventure!"
    redirect_to "/trips/#{trip_id}"
  end

  def destroy
    TripFacade.delete_trip(@user.google_id, params[:id])
    flash[:success] = "Trip has been Cancelled"
    redirect_to '/trips'
  end

  def edit
    @trip = TripFacade.trip_by_id(@user.google_id, params[:id])
  end

  def update
    TripFacade.update_trip(params[:id], params[:name], @user.google_id,
    params[:departure_date], params[:arrival_date])
    flash[:success] = "You've Updated Your Adventure"
    redirect_to "/trips/#{params[:id]}"
  end

  private

  def new_trip_params
    params.permit(:name, @user.google_id, :departure_date, :arrival_date)
  end

  def create_address(address_params)
   "#{address_params[0]} #{address_params[1]} #{address_params[2]} #{address_params[3]}"
  end

  def start_params(params)
    create_address([params[:start_address], params[:start_city],
                    params[:start_state], params[:start_zipcode]])
  end

  def end_params(params)
    create_address([params[:end_address], params[:end_city],
      params[:end_state], params[:end_zipcode]])
  end

  def trip_id(data)
    response = JSON.parse(data, symbollize_name: true)
    response["data"]["id"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user

  def show
    @trips = TripFacade.all_trips(@user.google_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripWeatherFe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://api.mqcdn.com/sdk/mapquest-js/v1.3.2/mapquest.js"></script>
    <link type="text/css" rel="stylesheet" href="https://api.mqcdn.com/sdk/mapquest-js/v1.3.2/mapquest.css"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {
      margin: 10;
      font-family: Arial, Helvetica, sans-serif;
      background-color: grey;

    }

    .topnav {
      position: relative;
      overflow: hidden;
      background-color: #000000;
    }

    .topnav a {
      float: left;
      color: #f2f2f2;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      font-size: 17px;
    }

    .topnav a:hover {
      background-color: #00BFFF;
      color: black;
    }

    .topnav a.active {
      background-color: #00BFFF;
      color: white;
    }

    .topnav-centered a {
      float: none;
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
    }

    .topnav-right {
      float: right;
    }

      @media screen and (max-width: 600px) {
        .topnav a, .topnav-right {
          float: none;
          display: block;
        }
        
        .topnav-centered a {
          position: relative;
          top: 0;
          left: 0;
          transform: none;
        }
      }
    </style>

      <div class="topnav"> <!-- Top navigation -->

      <div class="topnav-centered"> <!-- Centered link -->
        <a href="#TripWeather" class="active">TripWeather</a>
      </div>

      <% if current_user.nil? %>
        <%= link_to 'Home', root_path %> <!-- Left-aligned links (default) -->
      <% else %>
        <%= link_to 'Home', dashboard_path %> <!-- Left-aligned links (default) -->
      <% end %>

      <div class="topnav-right"> <!-- Right-aligned links -->
      <% if current_user.nil? %>
        <%= link_to "Log In", '/auth/google_oauth2', method: :post %>
      <% else %>
        <%= link_to "Log Out", logout_path, method: "delete" %>
      <% end %>
      </div>

    </div>
  </head>

  <body>

  <!DOCTYPE html>
<html>

  <body>
    
    <% flash.each do |type, message| %>
        <div class="custom-alert">
          <center><%= message %></center>
        </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/stops/edit.html.erb
  <%= form_with url: "/trips/#{@trip_id}/stops/#{@stop_id}/addresses/#{@address_id}", method: :put, local: true do |form| %>

  <p> <%= form.label :address, "Street Address" %>
  <%= form.text_field :address, required: true %> </p>

  <p> <%= form.label :city, "City" %>
  <%= form.text_field :city, required: true %> </p>

  <p> <%= form.label :state, "State" %>
  <%= form.select :state, options_for_select(us_states, "CO"), required: true %> </p>

  <p> <%= form.label :zipcode, "Zip Code" %>
  <%= form.number_field :zipcode, min: 0, max: 99999, required: true  %> </p>

  <p> <%= form.submit "Update Address" %> </p>

  <% end %>

app/views/trips/edit.html.erb
<%= form_with url: "/trips/#{@trip.id}", method: :put, local: true do |form| %>

  <p> <%= form.label :name, "Name your Adventure:" %>
  <%= form.text_field :name, value: @trip.name, required: true %> </p>

  <p> <%= form.label :departure_date, "When are you leaving?" %>
  <%= form.datetime_local_field :departure_date, min: Date.today, value: @trip.departure_date, required: true %> </p>

  <%= form.hidden_field :arrival_date, value: "2024-11-10T13:37:38.000Z" %>

  <p> <%= form.submit "Update Trip" %> </p>

<% end %>

app/views/trips/index.html.erb
<%= @user.first_name.titleize %>'s Trips <br>

<% @trips.each do |trip| %>
  <%= link_to trip.name, "/trips/#{trip.id}" %> <br>
  Departure Date: <%= trip.standard_time(trip.departure_date) %> <br>
  Arrival Date: <%= trip.standard_time(trip.arrival_date) %> <br>
  <br>


  <br>

<% end %>

app/views/trips/new.html.erb
<%= form_with url: '/trips', method: :post, local: true do |form| %>

  <p> <%= form.label :name, "Name your Adventure:" %>
  <%= form.text_field :name, required: true %> </p>

  <p> <%= form.label :departure_date, "When are you leaving?" %>
  <%= form.datetime_local_field :departure_date, min: Date.today, required: true %> </p>

  <%= form.hidden_field :arrival_date, value: "2024-11-10T13:37:38.000Z" %>

<h3> Departure Address </h3>

  <p> <%= form.label :start_address, "Street Address" %>
  <%= form.text_field :start_address, required: true %> </p>

  <p> <%= form.label :start_city, "City" %>
  <%= form.text_field :start_city, required: true %> </p>

  <p> <%= form.label :start_state, "State" %>
  <%= form.select :start_state, options_for_select(us_states, "CO"), required: true %> </p>

  <p> <%= form.label :start_zipcode, "Zip Code" %>
  <%= form.number_field :start_zipcode, min: 0, max: 99999, required: true  %> </p>

  <%= form.hidden_field :start_point, value: 0 %>

<h3> Arrival Address </h3>

  <p> <%= form.label :end_address, "Street Address" %>
  <%= form.text_field :end_address, required: true %> </p>

  <p> <%= form.label :end_city, "City" %>
  <%= form.text_field :end_city, required: true %> </p>

  <p> <%= form.label :end_state, "State" %>
  <%= form.select :end_state, options_for_select(us_states, "CO"), required: true %> </p>

  <p> <%= form.label :end_zipcode, "Zip Code" %>
  <%= form.number_field :end_zipcode, min: 0, max: 99999, required: true  %> </p>
  
  <%= form.hidden_field :end_point, value: 2 %>


  <p> <%= form.submit "Create Trip" %> </p>

<% end %>

app/views/trips/show.html.erb
<script type="text/javascript">
    window.onload = function() {
        // We understand this is a security risk
        L.mapquest.key = '<%= ENV['NAV_API'] %>';

        L.mapquest.map('map', {
            center: [0, 0],
            layers: L.mapquest.tileLayer('map'),
            zoom: 12
        });

        L.mapquest.directions().route({
            start: '<%= @start_address %>',
            end: '<%= @end_address %>'
        });
    };
</script>

<h1><%= @trip.name %></h1>
<%= button_to 'Delete Trip', "/trips/#{@trip.id}", method: :delete %><br>
<%= button_to 'Update Trip', "/trips/#{@trip.id}/edit", method: :get %><br>
<p>Departure: <%= @trip.standard_time(@trip.departure_date)%></p>
<p>Arrival: <%= @trip.standard_time(@trip.arrival_date)%></p>

<h3> Stops: </h3>

<div class="stops">
    <% stop_id = 0 %>
<p><% @stops.each do |stop| %></p>
    <div id="stop-<%=stop_id += 1%>">
      <%= stop.type_of_stop.titleize%> <%=stop.address%> <%= link_to "Edit Address", "/trips/#{stop.trip_id}/stops/#{stop.stop_id}/addresses/#{stop.address_id}/edit" %> <br>
    </div>
  <% end %>
  <br>
  <h3>Weather</h3>
  <strong>Your departure weather is;</strong>
  <p><%= @weather[0].detailed_forecast %></p>
  <strong>Your arrival weather is;</strong>
  <p><%= @weather[1].detailed_forecast %></p>
  <br>
  <h3>Navigation</h3>
  <div id="map" style="width: 100%; height: 530px;"></div><br>
  <strong>Total Trip Time:</strong> <span> <%= @nav.total_trip_time %></span><br>
  <strong>Total Distance in Miles:</strong> <span><%= @nav.total_distance %></span><br>
  <strong>Tolls:</strong> <span><%= @nav.has_toll_road %></span><br>
  <br>
  <h5>Step by Step Directions</h5>
  <ol>
    <% @nav.turn_by_turn_directions.each do |navigation| %>
      <li><%= navigation[0] %></li>
    <% end %>
  </ol>
</div>

app/views/users/new.html.erb
<%= form_with url: '/dashboard', method: :post do |form| %>

  <p> <%= form.label :full_name, "Full Name:" %>
  <%= form.text_field :full_name, required: true %> </p>

  <p> <%= form.label :first_name, "First Name:" %>
  <%= form.text_field :first_name, required: true %> </p>

  <p> <%= form.label :last_name, "First Name:" %>
  <%= form.text_field :last_name, required: true %> </p>

  <p> <%= form.label :email, "Email Address:" %>
  <%= form.text_field :email, required: true %> </p>

  <p> <%= form.label :image, "Profile Image" %>
  <%= form.file_field :image, value: nil %> </p>

  <p> <%= form.submit "Submit" %> </p>

<% end %>

app/views/users/show.html.erb
<h3><%= @user.email %>: Dashboard </h3>

  <img src=<%= @user.image %>> <br>

<div id="trips">
  <% @trips[0..2].each do |trip| %>
    <%= link_to trip.name, "/trips/#{trip.id}" %> <br>
    <%= trip.standard_time(trip.departure_date) %> <br>
    <%= trip.standard_time(trip.arrival_date) %> <br>
    <br>
    <br>
  <% end %>
</div>
<div id='map'></div>

<%= button_to "All Trips", '/trips', method: :get %> <br>
<%= button_to "Create a New Trip", '/trips/new', method: :get %> <br>

app/views/welcome/index.html.erb
<style>
p.outset {
  border-style: outset;
  background-color: white;
  }

h1 { text-align: center; }

p.body { text-align: center; }

div.margins {
  margin-top: 200px;
}
</style>
<div class="margins">
  <h1> <p class="outset"> Welcome To TripWeather</p> </h1> 
  <p class="body"> Please Log In to Continue  </p>

</div>